name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  QT_VERSION: 5.15.2

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v3

      - name: (2) Get all tags for correct version determination
        working-directory:  ${{ github.workspace }}
        run: |
            git fetch --all --tags -f
      
      - name: (3) Install Dependencies
        run: |
          sudo apt install qtbase5-dev qtchooser qtbase5-dev-tools libglu1-mesa-dev build-essential -y
          
      - name: (4) Export Qt Location
        run: |
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/qt/Qt/5.15.2/gcc_64/lib:$LD_LIBRARY_PATH
          echo $QT5_DIR

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/qt/Qt/5.15.2/gcc_64/lib/cmake

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}
